(()=>{"use strict";if(window.__AI_LOG_LOCAL_TOPBAR_V70)return;window.__AI_LOG_LOCAL_TOPBAR_V70=true;
const H=46;
function install(){if(!document.body)return;let style=document.getElementById("aiLogLocalTopbarCssV70");if(!style){style=document.createElement("style");style.id="aiLogLocalTopbarCssV70";/* [v342] 앱이 화면 가장자리까지 그린다(targetSdk 36). 상태표시줄 자리는 페이지가
   제 배경으로 덮어야 흰 띠가 안 생긴다. 상단바를 그만큼 키우고 본문도 같이 민다. */
style.textContent=`:root{--ailog-top:env(safe-area-inset-top,0px);--ailog-bottom:env(safe-area-inset-bottom,0px);
  /* [v362] 이 상단바는 position:fixed 에 z-index 가 매우 높다. 자리를 비우지 않으면
     보관함 대화상자 머리(제목·닫기)가 이 바 뒤로 들어가 손이 닿지 않는다.
     높이를 알려 두어 겹칠 수 있는 쪽이 비켜 갈 수 있게 한다. */
  --ailog-topbar:calc(${H}px + env(safe-area-inset-top,0px))}
html{scroll-padding-top:calc(${H}px + var(--ailog-top))!important}
body{padding-top:calc(${H}px + var(--ailog-top))!important;padding-bottom:var(--ailog-bottom)!important}.appFrame{min-height:calc(100dvh - ${H}px)}#aiLogLocalTopbarV70{position:fixed;left:0;right:0;top:0;height:calc(${H}px + var(--ailog-top));padding-top:var(--ailog-top);box-sizing:border-box;z-index:2147482500;display:flex;align-items:center;gap:2px;padding:0 4px;background:#fff;color:#26343b;border:0;border-bottom:1px solid color-mix(in srgb,var(--theme-line,var(--line)) 72%,#fff);box-shadow:none;font-family:system-ui,sans-serif}#aiLogLocalTopbarV70 .title{flex:1;text-align:center;font-size:13px;font-weight:800;letter-spacing:-.02em;pointer-events:none}#aiLogLocalTopbarV70 button{width:38px;height:38px;border:0;border-radius:9px;background:transparent;color:inherit;display:grid;place-items:center;font:800 21px/1 system-ui,sans-serif;padding:0;cursor:pointer}#aiLogLocalTopbarV70 button:active{background:var(--theme-background-soft,var(--paper2))}#aiLogLocalTopbarV70 button svg{width:20px;height:20px;display:block;pointer-events:none}.heroTools{display:none!important}.hero{grid-template-columns:minmax(0,1fr)!important}`;document.head.appendChild(style)}let bar=document.getElementById("aiLogLocalTopbarV70");if(!bar){bar=document.createElement("nav");bar.id="aiLogLocalTopbarV70";bar.setAttribute("aria-label","로그 발췌기 상단바");bar.innerHTML='<button type="button" data-action="web" aria-label="WebView로 돌아가기">‹</button><span class="title">로그 발췌기</span><button type="button" data-action="theme" aria-label="라이트·다크 모드">◐</button><button type="button" data-action="folder" aria-label="로그 보관함" title="불러오기"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 7.6A1.6 1.6 0 0 1 4.6 6h4.1a1.6 1.6 0 0 1 1.13.47l1.3 1.3h8.27A1.6 1.6 0 0 1 21 9.37v8.03A1.6 1.6 0 0 1 19.4 19H4.6A1.6 1.6 0 0 1 3 17.4Z"/></svg></button><button type="button" data-action="settings" aria-label="설정">⚙</button>';document.body.prepend(bar);bar.addEventListener("click",event=>{const a=event.target.closest("button")?.dataset.action;if(a==="web"){try{console.log("__AI_LOG_OPEN_ROFAN_ACTIVITY__")}catch(_){}}else if(a==="theme")document.getElementById("themeToggleButton")?.click();else if(a==="folder")document.getElementById("logLibraryButton")?.click();else if(a==="settings")document.getElementById("rofanSettingsButton")?.click()})}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
})();
