(()=>{"use strict";
if(window.__AI_LOG_SPEAKER_COLOR_PICKER_V79)return;window.__AI_LOG_SPEAKER_COLOR_PICKER_V79=true;
const IDS=new Set(["speakerUserColor","speakerCharacterColor"]),clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,Number(n)||0));
const norm=v=>{const m=String(v||"").trim().match(/^#?([0-9a-f]{6})$/i);return m?"#"+m[1].toLowerCase():""};
function hexToRgb(h){h=norm(h)||"#4f849c";return[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)]}
function rgbToHex(a){return"#"+a.map(v=>Math.round(clamp(v,0,255)).toString(16).padStart(2,"0")).join("")}
function rgbToHsv([r,g,b]){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0;if(d){if(mx===r)h=((g-b)/d)%6;else if(mx===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return[h,mx?d/mx:0,mx]}
function hsvToRgb(h,s,v){h=((Number(h)||0)%360+360)%360;s=clamp(s);v=clamp(v);const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let r=0,g=0,b=0;if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}return[(r+m)*255,(g+m)*255,(b+m)*255]}
let target=null,hsv=[195,.48,.61],draft="#4f849c";
function installCss(){if(document.getElementById("speakerColorPickerV79Css"))return;const s=document.createElement("style");s.id="speakerColorPickerV79Css";s.textContent=`
.miniColorControl.speakerColorControlV79{position:relative;cursor:pointer}
#speakerUserColor,#speakerCharacterColor{pointer-events:none!important}
#speakerColorModalV79[hidden]{display:none!important}
#speakerColorHueV79{-webkit-appearance:none!important;appearance:none!important;accent-color:auto!important;
  width:100%;height:18px!important;margin:10px 0 0;padding:0!important;border:0!important;border-radius:999px!important;
  background:linear-gradient(90deg,#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00)!important;background-image:linear-gradient(90deg,#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00)!important;
  box-shadow:inset 0 0 0 1px rgba(0,0,0,.14)!important}
#speakerColorHueV79::-webkit-slider-runnable-track{-webkit-appearance:none;height:18px;background:transparent!important;border:0!important;box-shadow:none!important}
#speakerColorHueV79::-webkit-slider-thumb{-webkit-appearance:none!important;width:16px;height:16px;border-radius:50%;
  background:#fff!important;border:2px solid rgba(0,0,0,.5);margin-top:1px;box-shadow:none!important}
#speakerColorSvV79{background:linear-gradient(to top,#000,transparent),linear-gradient(to right,#fff,hsl(var(--spk-h,195),100%,50%))!important}#speakerColorModalV79{position:fixed;inset:0;z-index:2147483600;display:grid;place-items:center;padding:18px;background:rgba(17,25,30,.38);backdrop-filter:blur(4px)}
#speakerColorDialogV79{width:min(420px,calc(100vw - 28px));border:1px solid var(--line,#c9dfe7);border-radius:22px;background:var(--paper,#fff);color:var(--ink,#1f2d36);box-shadow:0 18px 52px rgba(20,34,42,.24);padding:18px;display:grid;gap:14px}
#speakerColorDialogV79 h3{margin:0;font-size:18px;line-height:1.25}.speakerColorTopV79{display:grid;grid-template-columns:52px 1fr;gap:10px;align-items:center}.speakerColorPreviewV79{display:block;width:52px;height:52px;border-radius:16px;border:1px solid var(--line,#c9dfe7);box-shadow:inset 0 0 0 4px rgba(255,255,255,.72)}
#speakerColorHexV79{width:100%;min-height:44px;border:1px solid var(--line,#c9dfe7);border-radius:14px;background:#fff;color:var(--ink,#1f2d36);padding:0 13px;font:inherit}
#speakerColorSvV79{--h:195;position:relative;height:230px;border-radius:16px;overflow:hidden;touch-action:none;background:linear-gradient(to top,#000,transparent),linear-gradient(to right,#fff,hsl(var(--h),100%,50%));box-shadow:inset 0 0 0 1px rgba(0,0,0,.16)}
#speakerColorDotV79{position:absolute;width:18px;height:18px;border:3px solid #fff;border-radius:50%;transform:translate(-50%,-50%);box-shadow:0 0 0 1px rgba(0,0,0,.7),0 2px 8px rgba(0,0,0,.3);pointer-events:none}
#speakerColorHueV79{width:100%;height:22px;margin:0;appearance:none;border:none;border-radius:999px;background:linear-gradient(90deg,#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00)}#speakerColorHueV79::-webkit-slider-runnable-track{height:22px;border:none;border-radius:999px;background:transparent}#speakerColorHueV79::-moz-range-track{height:22px;border:none;border-radius:999px;background:transparent}#speakerColorHueV79::-moz-range-thumb{width:24px;height:24px;border-radius:50%;background:#fff;border:2px solid #52636c}#speakerColorHueV79::-webkit-slider-thumb{margin-top:-1px;appearance:none;width:24px;height:24px;border-radius:50%;background:#fff;border:2px solid #52636c;box-shadow:0 2px 8px rgba(0,0,0,.22)}
.speakerColorActionsV79{display:grid;grid-template-columns:1fr 1fr;gap:10px}.speakerColorActionsV79 button{min-height:46px;border-radius:14px;border:1px solid var(--line,#c9dfe7);font:inherit;font-weight:800;background:#fff;color:var(--ink,#1f2d36)}#speakerColorSaveV79{background:var(--theme-accent,var(--accent,#5eacc8));border-color:var(--theme-accent,var(--accent,#5eacc8));color:#fff}
html[data-theme="dark"] #speakerColorDialogV79{background:var(--paper,#182126)}html[data-theme="dark"] #speakerColorHexV79,html[data-theme="dark"] .speakerColorActionsV79 button:not(#speakerColorSaveV79){background:var(--inputBg,#11181c);color:var(--ink,#edf4f7)}
@media(max-width:480px){#speakerColorDialogV79{padding:15px;border-radius:19px}#speakerColorSvV79{height:210px}}
`;document.head.appendChild(s)}
function markup(){if(document.getElementById("speakerColorModalV79"))return;document.body.insertAdjacentHTML("beforeend",`<div id="speakerColorModalV79" hidden aria-hidden="true"><section id="speakerColorDialogV79" role="dialog" aria-modal="true" aria-labelledby="speakerColorTitleV79"><h3 id="speakerColorTitleV79">화자 색상</h3><div class="speakerColorTopV79"><i class="speakerColorPreviewV79" id="speakerColorPreviewV79"></i><input id="speakerColorHexV79" maxlength="7" spellcheck="false" inputmode="text" aria-label="HEX 색상"></div><div id="speakerColorSvV79"><i id="speakerColorDotV79"></i></div><input id="speakerColorHueV79" type="range" min="0" max="359" value="195" aria-label="색상 종류"><div class="speakerColorActionsV79"><button id="speakerColorCancelV79" type="button">취소</button><button id="speakerColorSaveV79" type="button">저장</button></div></section></div>`)}
function update(){draft=rgbToHex(hsvToRgb(...hsv));try{document.getElementById("speakerColorSvV79")?.style.setProperty("--spk-h",String(Math.round(hsv[0])))}catch(_){}const sv=document.getElementById("speakerColorSvV79"),dot=document.getElementById("speakerColorDotV79"),hue=document.getElementById("speakerColorHueV79"),hex=document.getElementById("speakerColorHexV79"),pre=document.getElementById("speakerColorPreviewV79");if(sv)sv.style.setProperty("--h",hsv[0]);if(dot){dot.style.left=hsv[1]*100+"%";dot.style.top=(1-hsv[2])*100+"%"}if(hue)hue.value=String(Math.round(hsv[0]));if(hex&&document.activeElement!==hex)hex.value=draft;if(pre)pre.style.background=draft}
function open(input,label){target=input;draft=norm(input?.value)||"#4f849c";hsv=rgbToHsv(hexToRgb(draft));const modal=document.getElementById("speakerColorModalV79");const title=document.getElementById("speakerColorTitleV79");if(title)title.textContent=(label?.querySelector("span")?.textContent||"화자 색상")+" 선택";update();modal.hidden=false;modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function close(){const modal=document.getElementById("speakerColorModalV79");if(!modal)return;modal.hidden=true;modal.setAttribute("aria-hidden","true");document.body.style.overflow="";target=null}
function save(){if(!target)return close();target.value=draft;target.dispatchEvent(new Event("input",{bubbles:true}));target.dispatchEvent(new Event("change",{bubbles:true}));close()}
function boot(){installCss();markup();for(const id of IDS){const input=document.getElementById(id);input?.closest?.(".miniColorControl")?.classList.add("speakerColorControlV79")}const modal=document.getElementById("speakerColorModalV79"),sv=document.getElementById("speakerColorSvV79"),hue=document.getElementById("speakerColorHueV79"),hex=document.getElementById("speakerColorHexV79");
 document.addEventListener("pointerdown",e=>{const label=e.target?.closest?.(".miniColorControl"),input=label?.querySelector?.('input[type="color"]');if(!input||!IDS.has(input.id))return;e.preventDefault();e.stopImmediatePropagation();open(input,label)},true);
 const pick=e=>{const r=sv.getBoundingClientRect();hsv=[hsv[0],clamp((e.clientX-r.left)/Math.max(1,r.width)),clamp(1-(e.clientY-r.top)/Math.max(1,r.height))];update()};
 sv?.addEventListener("pointerdown",e=>{sv.setPointerCapture?.(e.pointerId);pick(e)});sv?.addEventListener("pointermove",e=>{if(e.buttons||e.pressure>0)pick(e)});hue?.addEventListener("input",e=>{hsv[0]=+e.target.value;update()});hex?.addEventListener("change",e=>{const value=norm(e.target.value);if(value){hsv=rgbToHsv(hexToRgb(value));update()}else update()});
 document.getElementById("speakerColorCancelV79")?.addEventListener("click",close);document.getElementById("speakerColorSaveV79")?.addEventListener("click",save);/* 슬라이더를 끌다 배경 위에서 손을 떼면 click 의 target 이 modal 이 되어
   저장 없이 닫히던 문제. 누르기 시작한 곳이 배경일 때만 닫는다. */
let downOnBackdrop=false;
modal?.addEventListener("pointerdown",e=>{downOnBackdrop=(e.target===modal)});
modal?.addEventListener("click",e=>{if(e.target===modal&&downOnBackdrop)close();downOnBackdrop=false});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!modal.hidden)close()});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
