(()=>{"use strict";
if(window.__AI_LOG_THEME_V79_OVERRIDES)return;window.__AI_LOG_THEME_V79_OVERRIDES=true;
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,Number(n)||0));
const norm=v=>{const m=String(v||"").trim().match(/^#?([0-9a-f]{6})$/i);return m?"#"+m[1].toLowerCase():""};
const rgb=h=>{h=norm(h)||"#5eacc8";return[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)]};
const hex=a=>"#"+a.map(v=>Math.round(clamp(v,0,255)).toString(16).padStart(2,"0")).join("");
const mix=(a,b,n)=>hex(rgb(a).map((v,i)=>v+(rgb(b)[i]-v)*n));
function rgbHsv([r,g,b]){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0;if(d){if(mx===r)h=((g-b)/d)%6;else if(mx===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return[h,mx?d/mx:0,mx]}
function hsvRgb(h,s,v){h=((+h||0)%360+360)%360;s=clamp(s);v=clamp(v);const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let r=0,g=0,b=0;if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}return[(r+m)*255,(g+m)*255,(b+m)*255]}
function state(){let p={};try{p=window.AILogThemeV70?.get?.()||{}}catch(_){}let accent=norm(p.accent),background=norm(p.background);try{accent=accent||norm(localStorage.getItem("ai-log-theme-accent-v70"));background=background||norm(localStorage.getItem("ai-log-theme-background-v70"))}catch(_){}accent=accent||"#5eacc8";background=background||"#eef7fb";const [bh,bs,bv]=rgbHsv(rgb(background)),[ah,as,av]=rgbHsv(rgb(accent));const surface=hex(hsvRgb(bh,Math.min(.24,bs*.58),Math.max(.965,bv+(1-bv)*.72)));const surface2=hex(hsvRgb(bh,Math.min(.15,bs*.4),Math.max(.985,bv+(1-bv)*.86)));/* 버튼은 지정한 배경색의 파스텔(조금 더 밝은) 버전. 흰색에 42% 만 섞어 색기를 남긴다.
   배경은 지정색 그대로 두므로 배경 > 버튼 순으로 밝아진다. */
const button=(()=>{const pale=mix(background,"#ffffff",.42);const [ph,ps,pv]=rgbHsv(rgb(pale));
  const sat=bs<.04?ps:Math.min(.30,Math.max(.05,ps));   /* 무채색 배경에 색기가 끼지 않게 */
  return hex(hsvRgb(ph,sat,Math.min(1,Math.max(pv,bv+.03))))})();const accentPastel=hex(hsvRgb(ah,Math.min(.28,Math.max(.08,as*.34)),Math.max(.94,av+(1-av)*.76)));/* 카드 그림자가 페이지 전체를 덮어 배경을 탁하게 만들던 문제.
   그림자 색이 파란 회색(63,107,128) 으로 고정돼 있어 크림색 배경 위에서 색기를 빼앗았다.
   배경과 같은 계열의 어두운 색으로 바꾸고 번지는 폭도 줄인다. */
const shRgb=rgb(mix(background,"#000000",.62));
const shadow="0 10px 26px rgba("+shRgb.join(",")+",.10)";
const softShadow="0 6px 16px rgba("+shRgb.join(",")+",.07)";
const line=mix(background,accent,.22);const muted=hex(hsvRgb(ah,Math.min(.28,Math.max(.08,as*.36)),Math.min(.55,Math.max(.34,av*.62))));const muted2=hex(hsvRgb(ah,Math.min(.22,Math.max(.06,as*.28)),Math.min(.68,Math.max(.42,av*.72))));return{accent,background,surface,surface2,button,accentPastel,line,muted,muted2,shadow,softShadow}}
function apply(){const p=state(),r=document.documentElement;for(const[k,v]of Object.entries({"--v79-accent":p.accent,"--v79-page-bg":p.background,"--v79-surface":p.surface,"--v79-surface-2":p.surface2,"--v79-button":p.button,"--v79-accent-pastel":p.accentPastel,"--v79-line":p.line,"--v79-muted":p.muted,"--v79-muted-2":p.muted2}))r.style.setProperty(k,v);r.style.setProperty("--bg",p.background);r.style.setProperty("--paper",p.surface);r.style.setProperty("--paper2",p.surface2);r.style.setProperty("--inputBg","#ffffff");r.style.setProperty("--line",p.line);r.style.setProperty("--muted",p.muted);r.style.setProperty("--sub",p.muted2);r.style.setProperty("--shadow",p.shadow);r.style.setProperty("--softShadow",p.softShadow)}
function install(){if(!document.getElementById("aiLogThemeV79Overrides")){const s=document.createElement("style");s.id="aiLogThemeV79Overrides";s.textContent=`
html:not([data-theme="dark"]),html:not([data-theme="dark"]) body{background:var(--v79-page-bg)!important;background-image:none!important}
html:not([data-theme="dark"]) .appFrame,html:not([data-theme="dark"]) main,html:not([data-theme="dark"]) .mainColumn,html:not([data-theme="dark"]) #optionsBoard,html:not([data-theme="dark"]) #reviewBoard,html:not([data-theme="dark"]) .content{background:transparent!important}
html:not([data-theme="dark"]) .card,html:not([data-theme="dark"]) .sideCard,html:not([data-theme="dark"]) .hero,html:not([data-theme="dark"]) .statsCard,html:not([data-theme="dark"]) .editorBox,html:not([data-theme="dark"]) .reviewPanel,html:not([data-theme="dark"]) details.foldBlock,html:not([data-theme="dark"]) details.foldBlock>.blockBody,html:not([data-theme="dark"]) .reviewBlock,html:not([data-theme="dark"]) .riskPanel,html:not([data-theme="dark"]) .dupeCard,html:not([data-theme="dark"]) .containsKeywordGroup,html:not([data-theme="dark"]) .containsRow,html:not([data-theme="dark"]) .nextPromptFold,html:not([data-theme="dark"]) .rfS2Dialog,html:not([data-theme="dark"]) .rfS2Section,html:not([data-theme="dark"]) .chapterList,html:not([data-theme="dark"]) .bookPreviewWrap,html:not([data-theme="dark"]) .manualChapterEditor,html:not([data-theme="dark"]) .chapterPreviewItem,html:not([data-theme="dark"]) .unitChapterPreviewItem,html:not([data-theme="dark"]) .epubRichEditor,html:not([data-theme="dark"]) .workflowHint,html:not([data-theme="dark"]) .emptyState,html:not([data-theme="dark"]) .stat{background:var(--v79-surface)!important;border-color:var(--v79-line)!important}
html:not([data-theme="dark"]) .tabs,html:not([data-theme="dark"]) .filePicker,html:not([data-theme="dark"]) .flowList,html:not([data-theme="dark"]) .flowItem,html:not([data-theme="dark"]) .logLibraryTabs,html:not([data-theme="dark"]) .rfS2Notice,html:not([data-theme="dark"]) .badge,html:not([data-theme="dark"]) .saveBadge{background:var(--v79-surface-2)!important;border-color:var(--v79-line)!important}
html:not([data-theme="dark"]) input:not([type="range"]):not([type="checkbox"]):not([type="radio"]),html:not([data-theme="dark"]) select,html:not([data-theme="dark"]) textarea,html:not([data-theme="dark"]) option,html:not([data-theme="dark"]) .pastebox,html:not([data-theme="dark"]) .richResultBox,html:not([data-theme="dark"]) .control input,html:not([data-theme="dark"]) .control select,html:not([data-theme="dark"]) .control textarea,html:not([data-theme="dark"]) .rfS2Input,html:not([data-theme="dark"]) .rfS2Select,html:not([data-theme="dark"]) .resultFindBar input,html:not([data-theme="dark"]) .logRenameInput{background:#fff!important;color:var(--ink)!important;border-color:var(--v79-line)!important}
html:not([data-theme="dark"]) .logLibraryDialog,html:not([data-theme="dark"]) .sharedLibraryDialog{background:var(--v79-page-bg)!important;border-color:var(--v79-line)!important}
html:not([data-theme="dark"]) .logLibraryList,html:not([data-theme="dark"]) .logFileItem,html:not([data-theme="dark"]) .logFilePreview{background:#fff!important;border-color:var(--v79-line)!important}
html:not([data-theme="dark"]) .btn:not(.primary),html:not([data-theme="dark"]) .btn.subtle,html:not([data-theme="dark"]) .toggle:not(:has(input:checked)),html:not([data-theme="dark"]) .rfS2Button:not(.primary):not(.save),html:not([data-theme="dark"]) .rfS2Close,html:not([data-theme="dark"]) .rfS2FontChoiceButton,html:not([data-theme="dark"]) .rfS2FontMenu,html:not([data-theme="dark"]) .rfS2FontOption,html:not([data-theme="dark"]) .navIconBtn,html:not([data-theme="dark"]) .themeIconButton,html:not([data-theme="dark"]) .logLibraryIconBtn,html:not([data-theme="dark"]) .logLibraryImportBtn,html:not([data-theme="dark"]) .resultFindBar button,html:not([data-theme="dark"]) .miniColorControl{background:var(--v79-button)!important;color:var(--ink)!important;border-color:var(--v79-line)!important}
html:not([data-theme="dark"]) .tab:not(.active),html:not([data-theme="dark"]) .logLibraryTab:not(.active){background:transparent!important;color:var(--ink)!important}
html:not([data-theme="dark"]) .tab.active,html:not([data-theme="dark"]) .logLibraryTab.active,html:not([data-theme="dark"]) .btn.primary,html:not([data-theme="dark"]) .rfS2Button.primary,html:not([data-theme="dark"]) .rfS2Button.save,html:not([data-theme="dark"]) .miniChoiceBtn.active{background:var(--v79-accent)!important;border-color:var(--v79-accent)!important;color:#fff!important}
html:not([data-theme="dark"]) .toggle:has(input:checked),html:not([data-theme="dark"]) .reviewChoice.active{background:#fff!important;color:var(--ink)!important;border-color:var(--v79-accent)!important;box-shadow:0 0 0 2px color-mix(in srgb,var(--v79-accent) 18%,transparent)!important}
html:not([data-theme="dark"]) .toggle:has(input:checked)::before,html:not([data-theme="dark"]) .toggle:has(input:checked) .toggleDot,html:not([data-theme="dark"]) .reviewChoice.active::before{background:#fff!important;border-color:var(--v79-accent)!important;box-shadow:0 0 0 2px color-mix(in srgb,var(--v79-accent) 28%,#fff)!important}
html:not([data-theme="dark"]) .riskChip,html:not([data-theme="dark"]) .quickBackup,html:not([data-theme="dark"]) [data-mobile-backup],html:not([data-theme="dark"]) .postypeMini em,html:not([data-theme="dark"]) .chapterTocRow b,html:not([data-theme="dark"]) .flowDot{background:var(--v79-accent-pastel)!important;border-color:color-mix(in srgb,var(--v79-accent) 24%,#fff)!important;color:var(--ink)!important}
html:not([data-theme="dark"]) .sectionDesc,html:not([data-theme="dark"]) .heroText,html:not([data-theme="dark"]) .hint,html:not([data-theme="dark"]) .miniHelp,html:not([data-theme="dark"]) .rfS2Help,html:not([data-theme="dark"]) .rfS2Sub,html:not([data-theme="dark"]) .rfS2Status,html:not([data-theme="dark"]) .brandSub,html:not([data-theme="dark"]) .stat span,html:not([data-theme="dark"]) .editorLabel span:last-child,html:not([data-theme="dark"]) .resultFindStatus,html:not([data-theme="dark"]) .logFileMeta,html:not([data-theme="dark"]) .logLibraryPath,html:not([data-theme="dark"]) .logLibraryStatus{color:var(--v79-muted)!important}
html:not([data-theme="dark"]) .workflowHint,html:not([data-theme="dark"]) .flowItem,html:not([data-theme="dark"]) .eyebrow,html:not([data-theme="dark"]) .sectionHead,html:not([data-theme="dark"]) .editorLabel,html:not([data-theme="dark"]) .optionRow,html:not([data-theme="dark"]) .control,html:not([data-theme="dark"]) .badge,html:not([data-theme="dark"]) .rfS2Toggle{color:var(--v79-muted-2)!important}
html:not([data-theme="dark"]) .aiThemeV70Picker{background:var(--v79-surface-2)!important;border-color:var(--v79-line)!important}
/* 색 고르개의 무지개 띠와 채도판은 어떤 규칙으로도 덮이지 않게 못박는다 */
input.aiThemeV70Hue{background:linear-gradient(90deg,#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00)!important;-webkit-appearance:none;appearance:none;border:0!important;height:18px!important;border-radius:999px!important}
input.aiThemeV70Hue::-webkit-slider-runnable-track{background:transparent!important;height:18px}
input.aiThemeV70Hue::-webkit-slider-thumb{-webkit-appearance:none;width:16px;height:16px;border-radius:50%;background:#fff;border:2px solid rgba(0,0,0,.45);margin-top:1px}
.aiThemeV70SV{background:linear-gradient(to top,#000,transparent),linear-gradient(to right,#fff,hsl(var(--h),100%,50%))!important}
`;document.head.appendChild(s)}apply()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
addEventListener("ai-log-theme-v70-change",apply);new MutationObserver(apply).observe(document.documentElement,{attributes:true,attributeFilter:["data-theme"]});
})();

/* v71 레이어에서 이식된 고유 규칙(그 파일은 은퇴). 나머지 78개 선택자는 이 파일이 이미 덮고 있었다. */
const AI_V71_GRAFT=`.logLibraryTab{background:transparent!important;color:var(--ink)!important}
.toggle:has(input:checked){background:#fff!important;color:var(--ink)!important;border-color:var(--v78-accent)!important;box-shadow:0 0 0 2px color-mix(in srgb,var(--v78-accent) 18%,transparent)!important}`;
try{const st=document.createElement('style');st.id='aiV71Graft';st.textContent=AI_V71_GRAFT;document.head.appendChild(st);}catch(_){}
